import XCTest
@testable import i18nCore

final class IosStringsGeneratorTests: XCTestCase {

    private var tempDir: String!

    override func setUp() {
        super.setUp()
        tempDir = NSTemporaryDirectory().appending("ios-strings-test-\(UUID().uuidString)")
    }

    override func tearDown() {
        try? FileManager.default.removeItem(atPath: tempDir)
        super.tearDown()
    }

    func testGeneratesBaseLprojForDefaultLocale() throws {
        let data = makeData(entries: [makeEntry(key: "app_name", defaultValue: "My App")])
        try IosStringsGenerator.generate(data: data, outputDir: tempDir)

        let basePath = (tempDir as NSString).appendingPathComponent("Base.lproj/Localizable.strings")
        XCTAssertTrue(FileManager.default.fileExists(atPath: basePath))
    }

    func testGeneratesLocaleLprojForAdditionalLocales() throws {
        let data = makeData(
            entries: [makeEntry(key: "app_name", defaultValue: "My App", translations: ["en": "My App", "my": "မြန်မာ"])],
            additionalLocales: ["en", "my"]
        )
        try IosStringsGenerator.generate(data: data, outputDir: tempDir)

        XCTAssertTrue(FileManager.default.fileExists(atPath: (tempDir as NSString).appendingPathComponent("en.lproj/Localizable.strings")))
        XCTAssertTrue(FileManager.default.fileExists(atPath: (tempDir as NSString).appendingPathComponent("my.lproj/Localizable.strings")))
    }

    func testStringsFileFormat() throws {
        let data = makeData(entries: [makeEntry(key: "greeting", defaultValue: "Hello")])
        try IosStringsGenerator.generate(data: data, outputDir: tempDir)

        let content = try readFile("Base.lproj/Localizable.strings")
        XCTAssertTrue(content.contains("\"greeting\" = \"Hello\";"))
    }

    func testFiltersAndroidEntries() throws {
        let data = makeData(entries: [
            makeEntry(key: "android_key", platform: "android", defaultValue: "Android"),
            makeEntry(key: "ios_key", platform: "ios", defaultValue: "iOS"),
            makeEntry(key: "both_key", platform: "android,ios", defaultValue: "Both")
        ])
        try IosStringsGenerator.generate(data: data, outputDir: tempDir)

        let content = try readFile("Base.lproj/Localizable.strings")
        XCTAssertTrue(content.contains("ios_key"))
        XCTAssertTrue(content.contains("both_key"))
        XCTAssertFalse(content.contains("android_key"))
    }

    func testFallsBackToDefaultWhenTranslationMissing() throws {
        let data = makeData(
            entries: [makeEntry(key: "key", defaultValue: "Default", translations: [:])],
            additionalLocales: ["fr"]
        )
        try IosStringsGenerator.generate(data: data, outputDir: tempDir)

        let content = try readFile("fr.lproj/Localizable.strings")
        XCTAssertTrue(content.contains("\"key\" = \"Default\";"))
    }

    func testSkipsEmptyDefaultValues() throws {
        let data = makeData(entries: [
            makeEntry(key: "valid", defaultValue: "Value"),
            makeEntry(key: "empty", defaultValue: "")
        ])
        try IosStringsGenerator.generate(data: data, outputDir: tempDir)

        let content = try readFile("Base.lproj/Localizable.strings")
        XCTAssertTrue(content.contains("valid"))
        XCTAssertFalse(content.contains("\"empty\""))
    }

    func testCleansExistingOutputDirectory() throws {
        try FileManager.default.createDirectory(atPath: tempDir, withIntermediateDirectories: true)
        let oldFile = (tempDir as NSString).appendingPathComponent("old.txt")
        FileManager.default.createFile(atPath: oldFile, contents: nil)

        let data = makeData(entries: [makeEntry(key: "k", defaultValue: "v")])
        try IosStringsGenerator.generate(data: data, outputDir: tempDir)

        XCTAssertFalse(FileManager.default.fileExists(atPath: oldFile))
    }

    func testIncludesAutoGeneratedComment() throws {
        let data = makeData(entries: [makeEntry(key: "k", defaultValue: "v")])
        try IosStringsGenerator.generate(data: data, outputDir: tempDir)

        let content = try readFile("Base.lproj/Localizable.strings")
        XCTAssertTrue(content.hasPrefix("/* Auto-generated"))
    }

    // MARK: - Escape tests

    func testEscapesDoubleQuotes() {
        XCTAssertEqual(IosStringsGenerator.escape("Say \"Hi\""), "Say \\\"Hi\\\"")
    }

    func testEscapesBackslashes() {
        XCTAssertEqual(IosStringsGenerator.escape("C:\\Users"), "C:\\\\Users")
    }

    func testEscapesNewlines() {
        XCTAssertEqual(IosStringsGenerator.escape("Line1\nLine2"), "Line1\\nLine2")
    }

    func testEscapeStripsCarriageReturn() {
        XCTAssertEqual(IosStringsGenerator.escape("text\r\n"), "text\\n")
    }

    func testEscapeNoChangePlainText() {
        XCTAssertEqual(IosStringsGenerator.escape("Hello World"), "Hello World")
    }

    // MARK: - Helpers

    private func makeData(
        entries: [LocalizationEntry],
        additionalLocales: [String] = []
    ) -> LocalizationData {
        LocalizationData(defaultLocale: "default", additionalLocales: additionalLocales, entries: entries)
    }

    private func makeEntry(
        key: String,
        platform: String = "ios",
        defaultValue: String,
        translations: [String: String] = [:]
    ) -> LocalizationEntry {
        LocalizationEntry(key: key, platform: platform, defaultValue: defaultValue, translations: translations)
    }

    private func readFile(_ relativePath: String) throws -> String {
        let path = (tempDir as NSString).appendingPathComponent(relativePath)
        return try String(contentsOfFile: path, encoding: .utf8)
    }
}
