package io.github.fcat97.i18n.generator

import io.github.fcat97.i18n.parser.LocalizationData
import io.github.fcat97.i18n.parser.LocalizationEntry
import java.io.File
import java.nio.file.Files

/**
 * Generates iOS `.strings` files from localization data.
 *
 * Output structure:
 *   Base.lproj/Localizable.strings  -> default locale
 *   {locale}.lproj/Localizable.strings -> per-language locale
 *
 * Format of each file:
 *   "key" = "value";
 */
object IosStringsGenerator {
    private const val PLATFORM_IOS = "ios"
    private const val STRINGS_FILE_NAME = "Localizable.strings"
    private const val BASE_LPROJ = "Base.lproj"

    fun generate(data: LocalizationData, outputDir: File) {
        if (outputDir.exists()) {
            outputDir.deleteRecursively()
        }
        outputDir.mkdirs()

        val iosEntries = data.entries.filter { it.platform.contains(PLATFORM_IOS) }

        generateLocaleStrings(data.defaultLocale, iosEntries, outputDir, isDefault = true)

        data.additionalLocales.forEach { locale ->
            generateLocaleStrings(locale, iosEntries, outputDir, isDefault = false)
        }
    }

    private fun generateLocaleStrings(
        locale: String,
        entries: List<LocalizationEntry>,
        outputDir: File,
        isDefault: Boolean
    ) {
        val lprojDir = if (isDefault || locale == "default") {
            File(outputDir, BASE_LPROJ)
        } else {
            File(outputDir, "$locale.lproj")
        }

        lprojDir.mkdirs()
        val stringsFile = File(lprojDir, STRINGS_FILE_NAME)

        val content = buildString {
            appendLine("/* Auto-generated by i18n plugin. Do not edit manually. */")
            appendLine("")
            entries.forEach { entry ->
                val translation = if (!isDefault && locale != "default") {
                    entry.translations[locale]?.takeIf { it.isNotEmpty() } ?: entry.defaultValue
                } else {
                    entry.defaultValue
                }
                if (!translation.isNullOrEmpty()) {
                    val escapedKey = escapeStrings(entry.key)
                    val escapedValue = escapeStrings(translation)
                    appendLine("\"$escapedKey\" = \"$escapedValue\";")
                }
            }
        }

        Files.write(stringsFile.toPath(), content.toByteArray(Charsets.UTF_8))
    }

    /**
     * Escapes special characters for iOS .strings format:
     * - backslash must be escaped first to avoid double-escaping
     * - double quotes must be escaped
     * - newlines become \n
     */
    internal fun escapeStrings(text: String): String {
        return text
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "")
    }

    private fun StringBuilder.appendLine(line: String) {
        append(line)
        append("\n")
    }
}
