import Foundation

/// Generates classic `{locale}.lproj/Localizable.strings` files.
///
/// Output structure:
/// ```
/// outputDir/
///   Base.lproj/Localizable.strings    ← default locale
///   en.lproj/Localizable.strings
///   my.lproj/Localizable.strings
/// ```
///
/// File format:
/// ```
/// /* Auto-generated by i18n plugin. Do not edit manually. */
/// "key" = "value";
/// ```
public enum IosStringsGenerator {
    private static let fileName = "Localizable.strings"
    private static let baseLproj = "Base.lproj"
    private static let platform = "ios"

    public static func generate(data: LocalizationData, outputDir: String) throws {
        // Clean and recreate output directory
        let fm = FileManager.default
        if fm.fileExists(atPath: outputDir) {
            try fm.removeItem(atPath: outputDir)
        }
        try fm.createDirectory(atPath: outputDir, withIntermediateDirectories: true)

        let iosEntries = data.entries.filter { $0.platform.contains(platform) }

        // Default locale → Base.lproj
        try writeLocale(
            locale: data.defaultLocale,
            entries: iosEntries,
            outputDir: outputDir,
            lprojName: baseLproj,
            isDefault: true
        )

        // Additional locales
        for locale in data.additionalLocales {
            try writeLocale(
                locale: locale,
                entries: iosEntries,
                outputDir: outputDir,
                lprojName: "\(locale).lproj",
                isDefault: false
            )
        }
    }

    private static func writeLocale(
        locale: String,
        entries: [LocalizationEntry],
        outputDir: String,
        lprojName: String,
        isDefault: Bool
    ) throws {
        let lprojPath = (outputDir as NSString).appendingPathComponent(lprojName)
        try FileManager.default.createDirectory(atPath: lprojPath, withIntermediateDirectories: true)

        let filePath = (lprojPath as NSString).appendingPathComponent(fileName)

        var lines = ["/* Auto-generated by i18n plugin. Do not edit manually. */", ""]
        for entry in entries {
            let value: String
            if isDefault {
                value = entry.defaultValue
            } else {
                let translated = entry.translations[locale] ?? ""
                value = translated.isEmpty ? entry.defaultValue : translated
            }
            guard !value.isEmpty else { continue }
            lines.append("\"\(escape(entry.key))\" = \"\(escape(value))\";")
        }
        lines.append("")

        let content = lines.joined(separator: "\n")
        try content.write(toFile: filePath, atomically: true, encoding: .utf8)
    }

    /// Escape special characters for the `.strings` format.
    public static func escape(_ text: String) -> String {
        text
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "")
    }
}
